### ISSUE TITLE
Null check not backported from openjdk11 to openjdk8

### ISSUE THREAD

**Issue by ashish-250** [AdoptOpenJDK/openjdk-jdk8u#6]
Hi all, 
I am on a Centos7 machine. 
and using the following openjdk build.
_java -version_
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.232-b09, mixed mode)

During execution of our project, we are getting NPE at the following location :
net.sf.jasperreports.engine.JRRuntimeException: Error initializing graphic environment.
	at net.sf.jasperreports.engine.util.JRGraphEnvInitializer.initializeGraphEnv(JRGraphEnvInitializer.java:63)
	at net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(BaseReportFiller.java:122)
	at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:236)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:72)
	at net.sf.jasperreports.engine.fill.JRVerticalFiller.<init>(JRVerticalFiller.java:60)...........................
**Caused by: java.lang.NullPointerException
	at sun.awt.FcFontManager.getDefaultPlatformFont(FcFontManager.java:76)
	at sun.font.SunFontManager$2.run(SunFontManager.java:433)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)**
	at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442).................

On further investigation, I realized that the missing null check has already been added in openjdk11 but was not backported to previous versions at (FcFontManager.java:76).

Please backport the check to openjdk8 as well as there seems to be no workaround for this exception. 

Thanks

**Comment by karianna** [comment]
@ashishyadav2801 - This should be reported to the jdk8u-dev mailing list at OpenJDK (openjdk.java.net).

**Comment by gnu-andrew** [comment]
Fix is part of https://hg.openjdk.java.net/jdk-updates/jdk11u/rev/008f416a79cba9ec51b476b5761fc8ee564c13f8 which could be backported to 8u.
